/*
 * 支付宝开放平台API
 *
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 2024-10-16
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using AlipaySDKNet.OpenAPI.Client;
using AlipaySDKNet.OpenAPI.Model;
using AlipaySDKNet.OpenAPI.Util;
using AlipaySDKNet.OpenAPI.Util.Model;

namespace AlipaySDKNet.OpenAPI.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAlipayMarketingActivityGoodsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 查询活动适用商品
        /// </summary>
        /// <remarks>
        /// 通过此接口可查询活动的可用或不可用商品,判断是否在该商品可用，来决定是否展示。
        /// </remarks>
        /// <exception cref="AlipaySDKNet.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId">活动id</param>
        /// <param name="merchantId">商户PID,默认为当前接口调用商户。 (optional)</param>
        /// <param name="goodsUseType">活动单品类型。 (optional)</param>
        /// <param name="pageNum">分页查询页码。 限制: 必须为大于0的整数 (optional)</param>
        /// <param name="pageSize">分页查询单页数据条数。 限制: 1.必须为大于0的整数 2.每页最大值为20 (optional)</param>
        /// <param name="productVersion">版本号  枚举值: 2.0.0 (optional)</param>
        /// <param name="merchantAccessMode">商户接入模式 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="customizedParams">customizedParams</param>
        /// <returns>AlipayMarketingActivityGoodsBatchqueryResponseModel</returns>
        AlipayMarketingActivityGoodsBatchqueryResponseModel Batchquery(string activityId, string merchantId = default(string), string goodsUseType = default(string), int? pageNum = default(int?), int? pageSize = default(int?), string productVersion = default(string), string merchantAccessMode = default(string), int operationIndex = 0, CustomizedParams customizedParams = null);

        /// <summary>
        /// 查询活动适用商品
        /// </summary>
        /// <remarks>
        /// 通过此接口可查询活动的可用或不可用商品,判断是否在该商品可用，来决定是否展示。
        /// </remarks>
        /// <exception cref="AlipaySDKNet.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId">活动id</param>
        /// <param name="merchantId">商户PID,默认为当前接口调用商户。 (optional)</param>
        /// <param name="goodsUseType">活动单品类型。 (optional)</param>
        /// <param name="pageNum">分页查询页码。 限制: 必须为大于0的整数 (optional)</param>
        /// <param name="pageSize">分页查询单页数据条数。 限制: 1.必须为大于0的整数 2.每页最大值为20 (optional)</param>
        /// <param name="productVersion">版本号  枚举值: 2.0.0 (optional)</param>
        /// <param name="merchantAccessMode">商户接入模式 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="customizedParams">customizedParams</param>
        /// <returns>ApiResponse of AlipayMarketingActivityGoodsBatchqueryResponseModel</returns>
        ApiResponse<AlipayMarketingActivityGoodsBatchqueryResponseModel> BatchqueryWithHttpInfo(string activityId, string merchantId = default(string), string goodsUseType = default(string), int? pageNum = default(int?), int? pageSize = default(int?), string productVersion = default(string), string merchantAccessMode = default(string), int operationIndex = 0, CustomizedParams customizedParams = null);
        #endregion Synchronous Operations
    }


    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAlipayMarketingActivityGoodsApi : IAlipayMarketingActivityGoodsApiSync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AlipayMarketingActivityGoodsApi : IAlipayMarketingActivityGoodsApi
    {
        private AlipaySDKNet.OpenAPI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AlipayMarketingActivityGoodsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AlipayMarketingActivityGoodsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlipayMarketingActivityGoodsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AlipayMarketingActivityGoodsApi(string basePath)
        {
            this.Configuration = AlipaySDKNet.OpenAPI.Client.Configuration.MergeConfigurations(
                AlipaySDKNet.OpenAPI.Client.GlobalConfiguration.Instance,
                new AlipaySDKNet.OpenAPI.Client.Configuration { BasePath = basePath }
            );
            this.Client = new AlipaySDKNet.OpenAPI.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = AlipaySDKNet.OpenAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlipayMarketingActivityGoodsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AlipayMarketingActivityGoodsApi(AlipaySDKNet.OpenAPI.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AlipaySDKNet.OpenAPI.Client.Configuration.MergeConfigurations(
                AlipaySDKNet.OpenAPI.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new AlipaySDKNet.OpenAPI.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = AlipaySDKNet.OpenAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlipayMarketingActivityGoodsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AlipayMarketingActivityGoodsApi(AlipaySDKNet.OpenAPI.Client.ISynchronousClient client, AlipaySDKNet.OpenAPI.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.Configuration = configuration;
            this.ExceptionFactory = AlipaySDKNet.OpenAPI.Client.Configuration.DefaultExceptionFactory;
        }


        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AlipaySDKNet.OpenAPI.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AlipaySDKNet.OpenAPI.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AlipaySDKNet.OpenAPI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// 查询活动适用商品 通过此接口可查询活动的可用或不可用商品,判断是否在该商品可用，来决定是否展示。
        /// </summary>
        /// <exception cref="AlipaySDKNet.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId">活动id</param>
        /// <param name="merchantId">商户PID,默认为当前接口调用商户。 (optional)</param>
        /// <param name="goodsUseType">活动单品类型。 (optional)</param>
        /// <param name="pageNum">分页查询页码。 限制: 必须为大于0的整数 (optional)</param>
        /// <param name="pageSize">分页查询单页数据条数。 限制: 1.必须为大于0的整数 2.每页最大值为20 (optional)</param>
        /// <param name="productVersion">版本号  枚举值: 2.0.0 (optional)</param>
        /// <param name="merchantAccessMode">商户接入模式 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="customizedParams">customizedParams</param>
        /// <returns>AlipayMarketingActivityGoodsBatchqueryResponseModel</returns>
        public AlipayMarketingActivityGoodsBatchqueryResponseModel Batchquery(string activityId, string merchantId = default(string), string goodsUseType = default(string), int? pageNum = default(int?), int? pageSize = default(int?), string productVersion = default(string), string merchantAccessMode = default(string), int operationIndex = 0, CustomizedParams customizedParams = null)
        {
            AlipaySDKNet.OpenAPI.Client.ApiResponse<AlipayMarketingActivityGoodsBatchqueryResponseModel> localVarResponse = BatchqueryWithHttpInfo(activityId, merchantId, goodsUseType, pageNum, pageSize, productVersion, merchantAccessMode, operationIndex, customizedParams);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 查询活动适用商品 通过此接口可查询活动的可用或不可用商品,判断是否在该商品可用，来决定是否展示。
        /// </summary>
        /// <exception cref="AlipaySDKNet.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId">活动id</param>
        /// <param name="merchantId">商户PID,默认为当前接口调用商户。 (optional)</param>
        /// <param name="goodsUseType">活动单品类型。 (optional)</param>
        /// <param name="pageNum">分页查询页码。 限制: 必须为大于0的整数 (optional)</param>
        /// <param name="pageSize">分页查询单页数据条数。 限制: 1.必须为大于0的整数 2.每页最大值为20 (optional)</param>
        /// <param name="productVersion">版本号  枚举值: 2.0.0 (optional)</param>
        /// <param name="merchantAccessMode">商户接入模式 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="customizedParams">customizedParams</param>
        /// <returns>ApiResponse of AlipayMarketingActivityGoodsBatchqueryResponseModel</returns>
        public AlipaySDKNet.OpenAPI.Client.ApiResponse<AlipayMarketingActivityGoodsBatchqueryResponseModel> BatchqueryWithHttpInfo(string activityId, string merchantId = default(string), string goodsUseType = default(string), int? pageNum = default(int?), int? pageSize = default(int?), string productVersion = default(string), string merchantAccessMode = default(string), int operationIndex = 0, CustomizedParams customizedParams = null)
        {
            // verify the required path parameter 'activityId' is set
            if (activityId == null)
            {
                throw new AlipaySDKNet.OpenAPI.Client.ApiException(400, "Missing required parameter 'activityId' when calling AlipayMarketingActivityGoodsApi->Batchquery");
            }

            AlipaySDKNet.OpenAPI.Client.RequestOptions localVarRequestOptions = new AlipaySDKNet.OpenAPI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AlipaySDKNet.OpenAPI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AlipaySDKNet.OpenAPI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (activityId != null)
            {
                localVarRequestOptions.PathParameters.Add("activity_id", AlipaySDKNet.OpenAPI.Client.ClientUtils.ParameterToString(activityId)); // path parameter
            }
            if (merchantId != null)
            {
                localVarRequestOptions.QueryParameters.Add(AlipaySDKNet.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "merchant_id", merchantId));
            }
            if (goodsUseType != null)
            {
                localVarRequestOptions.QueryParameters.Add(AlipaySDKNet.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "goods_use_type", goodsUseType));
            }
            if (pageNum != null)
            {
                localVarRequestOptions.QueryParameters.Add(AlipaySDKNet.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "page_num", pageNum));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(AlipaySDKNet.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "page_size", pageSize));
            }
            if (productVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(AlipaySDKNet.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "product_version", productVersion));
            }
            if (merchantAccessMode != null)
            {
                localVarRequestOptions.QueryParameters.Add(AlipaySDKNet.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "merchant_access_mode", merchantAccessMode));
            }

            localVarRequestOptions.Operation = "AlipayMarketingActivityGoodsApi.Batchquery";
            localVarRequestOptions.OperationIndex = operationIndex;

            
            if (customizedParams != null)
            {
                //额外query参数
                if (customizedParams.QueryParams != null && customizedParams.QueryParams.Count > 0)
                {
                    foreach (var param in customizedParams.QueryParams)
                    {
                        localVarRequestOptions.QueryParameters.Add(param.Key, param.Value);
                    }
                }

                if (!string.IsNullOrEmpty(customizedParams.AppAuthToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("alipay-app-auth-token", customizedParams.AppAuthToken);
                }
                
                //额外非全局header参数
                if (customizedParams.HeaderParams != null && customizedParams.HeaderParams.Count > 0)
                {
                    foreach (var param in customizedParams.HeaderParams)
                    {
                        localVarRequestOptions.HeaderParameters.Add(param.Key, param.Value);
                    }
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<AlipayMarketingActivityGoodsBatchqueryResponseModel>("/v3/alipay/marketing/activity/{activity_id}/goods/batchquery", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Batchquery", localVarResponse);
                if (_exception != null)
                {
                    if (_exception is ApiException exception && exception.ErrorContent != null)
                    {
                        try
                        {
                            exception.ErrorObject = AlipayMarketingActivityGoodsBatchqueryDefaultResponse.FromJson(exception.ErrorContent.ToString());
                        }
                        catch (Exception e)
                        {
                            AlipayLogger.logBizWarn("解析default body内容失败", e);
                        }
                    }
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
