/*
 * 支付宝开放平台API
 *
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 2023-07-17
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AlipaySDKNet.OpenAPI.Client.OpenAPIDateConverter;

namespace AlipaySDKNet.OpenAPI.Model
{
    /// <summary>
    /// AlipayOpenPublicLifeMsgSendErrorResponseModel
    /// </summary>
    [DataContract(Name = "AlipayOpenPublicLifeMsgSendErrorResponseModel")]
    public partial class AlipayOpenPublicLifeMsgSendErrorResponseModel : IEquatable<AlipayOpenPublicLifeMsgSendErrorResponseModel>, IValidatableObject
    {
        /// <summary>
        /// 错误码
        /// </summary>
        /// <value>错误码</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CodeEnum
        {
            /// <summary>
            /// Enum ILLEGALBIZPARAMS for value: ILLEGAL_BIZ_PARAMS
            /// </summary>
            [EnumMember(Value = "ILLEGAL_BIZ_PARAMS")]
            ILLEGALBIZPARAMS = 1,

            /// <summary>
            /// Enum LIFEAPPNOTEXISTED for value: LIFE_APP_NOT_EXISTED
            /// </summary>
            [EnumMember(Value = "LIFE_APP_NOT_EXISTED")]
            LIFEAPPNOTEXISTED = 2,

            /// <summary>
            /// Enum INVALIDLIFEAPPMSGTYPE for value: INVALID_LIFE_APP_MSG_TYPE
            /// </summary>
            [EnumMember(Value = "INVALID_LIFE_APP_MSG_TYPE")]
            INVALIDLIFEAPPMSGTYPE = 3,

            /// <summary>
            /// Enum LIFEAPPMSGTITLEEMPTY for value: LIFE_APP_MSG_TITLE_EMPTY
            /// </summary>
            [EnumMember(Value = "LIFE_APP_MSG_TITLE_EMPTY")]
            LIFEAPPMSGTITLEEMPTY = 4,

            /// <summary>
            /// Enum LIFEAPPCOVERUPLOADERROR for value: LIFE_APP_COVER_UPLOAD_ERROR
            /// </summary>
            [EnumMember(Value = "LIFE_APP_COVER_UPLOAD_ERROR")]
            LIFEAPPCOVERUPLOADERROR = 5,

            /// <summary>
            /// Enum LIFEAPPVIDEIOINFOMISSED for value: LIFE_APP_VIDEIO_INFO_MISSED
            /// </summary>
            [EnumMember(Value = "LIFE_APP_VIDEIO_INFO_MISSED")]
            LIFEAPPVIDEIOINFOMISSED = 6,

            /// <summary>
            /// Enum LIFEAPPMSGCONTENTEMPTY for value: LIFE_APP_MSG_CONTENT_EMPTY
            /// </summary>
            [EnumMember(Value = "LIFE_APP_MSG_CONTENT_EMPTY")]
            LIFEAPPMSGCONTENTEMPTY = 7,

            /// <summary>
            /// Enum LIFEAPPMSGRAWURLEMPTY for value: LIFE_APP_MSG_RAW_URL_EMPTY
            /// </summary>
            [EnumMember(Value = "LIFE_APP_MSG_RAW_URL_EMPTY")]
            LIFEAPPMSGRAWURLEMPTY = 8,

            /// <summary>
            /// Enum LIFEAPPMSGCATEGORYEMPTY for value: LIFE_APP_MSG_CATEGORY_EMPTY
            /// </summary>
            [EnumMember(Value = "LIFE_APP_MSG_CATEGORY_EMPTY")]
            LIFEAPPMSGCATEGORYEMPTY = 9,

            /// <summary>
            /// Enum LIFEAPPFILETOOLARGE for value: LIFE_APP_FILE_TOO_LARGE
            /// </summary>
            [EnumMember(Value = "LIFE_APP_FILE_TOO_LARGE")]
            LIFEAPPFILETOOLARGE = 10,

            /// <summary>
            /// Enum LIFEAPPINVALIDIMAGEBYTES for value: LIFE_APP_INVALID_IMAGE_BYTES
            /// </summary>
            [EnumMember(Value = "LIFE_APP_INVALID_IMAGE_BYTES")]
            LIFEAPPINVALIDIMAGEBYTES = 11,

            /// <summary>
            /// Enum LIFEAPPMSGCONTENTILLEGAL for value: LIFE_APP_MSG_CONTENT_ILLEGAL
            /// </summary>
            [EnumMember(Value = "LIFE_APP_MSG_CONTENT_ILLEGAL")]
            LIFEAPPMSGCONTENTILLEGAL = 12,

            /// <summary>
            /// Enum LIFEAPPMSGSENDERROR for value: LIFE_APP_MSG_SEND_ERROR
            /// </summary>
            [EnumMember(Value = "LIFE_APP_MSG_SEND_ERROR")]
            LIFEAPPMSGSENDERROR = 13,

            /// <summary>
            /// Enum LIFEAPPMSGDESCEMPTY for value: LIFE_APP_MSG_DESC_EMPTY
            /// </summary>
            [EnumMember(Value = "LIFE_APP_MSG_DESC_EMPTY")]
            LIFEAPPMSGDESCEMPTY = 14,

            /// <summary>
            /// Enum LIFEAPPMSGTITLETOOLONG for value: LIFE_APP_MSG_TITLE_TOO_LONG
            /// </summary>
            [EnumMember(Value = "LIFE_APP_MSG_TITLE_TOO_LONG")]
            LIFEAPPMSGTITLETOOLONG = 15,

            /// <summary>
            /// Enum LIFEAPPVIDEOSOURCENOTEXIST for value: LIFE_APP_VIDEO_SOURCE_NOT_EXIST
            /// </summary>
            [EnumMember(Value = "LIFE_APP_VIDEO_SOURCE_NOT_EXIST")]
            LIFEAPPVIDEOSOURCENOTEXIST = 16,

            /// <summary>
            /// Enum LIFEAPPVIDEOLENGTHNOTRIGHT for value: LIFE_APP_VIDEO_LENGTH_NOT_RIGHT
            /// </summary>
            [EnumMember(Value = "LIFE_APP_VIDEO_LENGTH_NOT_RIGHT")]
            LIFEAPPVIDEOLENGTHNOTRIGHT = 17,

            /// <summary>
            /// Enum LIFEMSGVIDEOSAMPLESMISSING for value: LIFE_MSG_VIDEO_SAMPLES_MISSING
            /// </summary>
            [EnumMember(Value = "LIFE_MSG_VIDEO_SAMPLES_MISSING")]
            LIFEMSGVIDEOSAMPLESMISSING = 18,

            /// <summary>
            /// Enum LIFEAPPVIDEOLACKTEMPURL for value: LIFE_APP_VIDEO_LACK_TEMP_URL
            /// </summary>
            [EnumMember(Value = "LIFE_APP_VIDEO_LACK_TEMP_URL")]
            LIFEAPPVIDEOLACKTEMPURL = 19

        }


        /// <summary>
        /// 错误码
        /// </summary>
        /// <value>错误码</value>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = false)]
        public CodeEnum Code { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AlipayOpenPublicLifeMsgSendErrorResponseModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AlipayOpenPublicLifeMsgSendErrorResponseModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AlipayOpenPublicLifeMsgSendErrorResponseModel" /> class.
        /// </summary>
        /// <param name="code">错误码 (required).</param>
        /// <param name="links">解决方案链接.</param>
        /// <param name="message">错误描述 (required).</param>
        public AlipayOpenPublicLifeMsgSendErrorResponseModel(CodeEnum code = default(CodeEnum), string links = default(string), string message = default(string))
        {
            this.Code = code;
            // to ensure "message" is required (not null)
            // if (message == null)
            // {
            //     throw new ArgumentNullException("message is a required property for AlipayOpenPublicLifeMsgSendErrorResponseModel and cannot be null");
            // }
            this.Message = message;
            this.Links = links;
        }

        /// <summary>
        /// 解决方案链接
        /// </summary>
        /// <value>解决方案链接</value>
        [DataMember(Name = "links", EmitDefaultValue = false)]
        public string Links { get; set; }

        /// <summary>
        /// 错误描述
        /// </summary>
        /// <value>错误描述</value>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AlipayOpenPublicLifeMsgSendErrorResponseModel {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AlipayOpenPublicLifeMsgSendErrorResponseModel);
        }

        /// <summary>
        /// Returns true if AlipayOpenPublicLifeMsgSendErrorResponseModel instances are equal
        /// </summary>
        /// <param name="input">Instance of AlipayOpenPublicLifeMsgSendErrorResponseModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AlipayOpenPublicLifeMsgSendErrorResponseModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Code == input.Code ||
                    this.Code.Equals(input.Code)
                ) && 
                (
                    this.Links == input.Links ||
                    (this.Links != null &&
                    this.Links.Equals(input.Links))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Code.GetHashCode();
                if (this.Links != null)
                {
                    hashCode = (hashCode * 59) + this.Links.GetHashCode();
                }
                if (this.Message != null)
                {
                    hashCode = (hashCode * 59) + this.Message.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
