/*
 * 支付宝开放平台API
 *
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 2024-10-08
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AlipaySDKNet.OpenAPI.Client.OpenAPIDateConverter;

namespace AlipaySDKNet.OpenAPI.Model
{
    /// <summary>
    /// AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel
    /// </summary>
    [DataContract(Name = "AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel")]
    public partial class AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel : IEquatable<AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel>, IValidatableObject
    {
        /// <summary>
        /// 错误码
        /// </summary>
        /// <value>错误码</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CodeEnum
        {
            /// <summary>
            /// Enum INVOICENOTEXIST for value: INVOICE_NOT_EXIST
            /// </summary>
            [EnumMember(Value = "INVOICE_NOT_EXIST")]
            INVOICENOTEXIST = 1,

            /// <summary>
            /// Enum INVOICEEXPENSESTATUSREPEAT for value: INVOICE_EXPENSE_STATUS_REPEAT
            /// </summary>
            [EnumMember(Value = "INVOICE_EXPENSE_STATUS_REPEAT")]
            INVOICEEXPENSESTATUSREPEAT = 2,

            /// <summary>
            /// Enum PERMISSIONDENIED for value: PERMISSION_DENIED
            /// </summary>
            [EnumMember(Value = "PERMISSION_DENIED")]
            PERMISSIONDENIED = 3,

            /// <summary>
            /// Enum EXPENSEINVOICEDETAILURLCHECK for value: EXPENSE_INVOICE_DETAIL_URL_CHECK
            /// </summary>
            [EnumMember(Value = "EXPENSE_INVOICE_DETAIL_URL_CHECK")]
            EXPENSEINVOICEDETAILURLCHECK = 4,

            /// <summary>
            /// Enum INVOICEHAVEPROCESSINGEXPENSE for value: INVOICE_HAVE_PROCESSING_EXPENSE
            /// </summary>
            [EnumMember(Value = "INVOICE_HAVE_PROCESSING_EXPENSE")]
            INVOICEHAVEPROCESSINGEXPENSE = 5,

            /// <summary>
            /// Enum INVOICEHAVEEXPENSE for value: INVOICE_HAVE_EXPENSE
            /// </summary>
            [EnumMember(Value = "INVOICE_HAVE_EXPENSE")]
            INVOICEHAVEEXPENSE = 6,

            /// <summary>
            /// Enum EXPENSEORDERNODISAGREE for value: EXPENSE_ORDER_NO_DISAGREE
            /// </summary>
            [EnumMember(Value = "EXPENSE_ORDER_NO_DISAGREE")]
            EXPENSEORDERNODISAGREE = 7,

            /// <summary>
            /// Enum EXPENSEINVOICEDISABLE for value: EXPENSE_INVOICE_DISABLE
            /// </summary>
            [EnumMember(Value = "EXPENSE_INVOICE_DISABLE")]
            EXPENSEINVOICEDISABLE = 8,

            /// <summary>
            /// Enum EXPENSENOTREACHPROCESSING for value: EXPENSE_NOT_REACH_PROCESSING
            /// </summary>
            [EnumMember(Value = "EXPENSE_NOT_REACH_PROCESSING")]
            EXPENSENOTREACHPROCESSING = 9,

            /// <summary>
            /// Enum EXPENSEAPPLYIDREPEAT for value: EXPENSE_APPLY_ID_REPEAT
            /// </summary>
            [EnumMember(Value = "EXPENSE_APPLY_ID_REPEAT")]
            EXPENSEAPPLYIDREPEAT = 10,

            /// <summary>
            /// Enum PARAMETERILLEGAL for value: PARAMETER_ILLEGAL
            /// </summary>
            [EnumMember(Value = "PARAMETER_ILLEGAL")]
            PARAMETERILLEGAL = 11,

            /// <summary>
            /// Enum EXPENSEBUSINESSTIMEERROR for value: EXPENSE_BUSINESS_TIME_ERROR
            /// </summary>
            [EnumMember(Value = "EXPENSE_BUSINESS_TIME_ERROR")]
            EXPENSEBUSINESSTIMEERROR = 12,

            /// <summary>
            /// Enum SYSTEMERROR for value: SYSTEM_ERROR
            /// </summary>
            [EnumMember(Value = "SYSTEM_ERROR")]
            SYSTEMERROR = 13,

            /// <summary>
            /// Enum QUERYTAXNONOTEQUALCERTIFYNO for value: QUERY_TAX_NO_NOT_EQUAL_CERTIFY_NO
            /// </summary>
            [EnumMember(Value = "QUERY_TAX_NO_NOT_EQUAL_CERTIFY_NO")]
            QUERYTAXNONOTEQUALCERTIFYNO = 14,

            /// <summary>
            /// Enum PRODUCTISEMPTY for value: PRODUCT_IS_EMPTY
            /// </summary>
            [EnumMember(Value = "PRODUCT_IS_EMPTY")]
            PRODUCTISEMPTY = 15

        }


        /// <summary>
        /// 错误码
        /// </summary>
        /// <value>错误码</value>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public CodeEnum Code { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel" /> class.
        /// </summary>
        /// <param name="code">错误码 (required).</param>
        /// <param name="links">解决方案链接.</param>
        /// <param name="message">错误描述 (required).</param>
        public AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel(CodeEnum code = default(CodeEnum), string links = default(string), string message = default(string))
        {
            this.Code = code;
            // to ensure "message" is required (not null)
            // if (message == null)
            // {
            //     throw new ArgumentNullException("message is a required property for AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel and cannot be null");
            // }
            this.Message = message;
            this.Links = links;
        }

        /// <summary>
        /// 解决方案链接
        /// </summary>
        /// <value>解决方案链接</value>
        [DataMember(Name = "links", EmitDefaultValue = false)]
        public string Links { get; set; }

        /// <summary>
        /// 错误描述
        /// </summary>
        /// <value>错误描述</value>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel);
        }

        /// <summary>
        /// Returns true if AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel instances are equal
        /// </summary>
        /// <param name="input">Instance of AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Code == input.Code ||
                    this.Code.Equals(input.Code)
                ) && 
                (
                    this.Links == input.Links ||
                    (this.Links != null &&
                    this.Links.Equals(input.Links))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Code.GetHashCode();
                if (this.Links != null)
                {
                    hashCode = (hashCode * 59) + this.Links.GetHashCode();
                }
                if (this.Message != null)
                {
                    hashCode = (hashCode * 59) + this.Message.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
